LittleFarmCakes/Controllers/CartsController.cs
using LittleFarmCakes.Data;
using LittleFarmCakes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace LittleFarmCakes.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IWebHostEnvironment _env;
        public CartsController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager,
        IWebHostEnvironment env
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }
        public IActionResult Index()
        {

            var userId = _userManager.GetUserId(User);
            var carts = db.Carts.Include("Product").Where(c => c.UserId == userId);

            ViewBag.Products = carts;

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "User,Contributor,Admin")]
        public IActionResult AddToCart(Cart cart)
        {

            string userId = _userManager.GetUserId(User);
            try
            {
                Cart oldCart = db.Carts.Where(c => c.ProductId == cart.ProductId && c.UserId == userId).First();

                oldCart.Count += cart.Count;
            }
            catch
            {
                cart.UserId = userId;
                db.Carts.Add(cart);
            }
            db.SaveChanges();

            TempData["Message"] = "Produsele au fost adaugate in cos";

            //return RedirectToAction("Show", "Products", new {id = cart.ProductId});
            return RedirectToAction("Show","Products", new {id = cart.ProductId});
        }

        [HttpPost]
        [Authorize(Roles = "User,Contributor,Admin")]

        public IActionResult Delete(Cart cart)
        {
            var userId = _userManager.GetUserId(User);
            try
            {
                var oldCart = db.Carts.Where(c => c.Product.Id == cart.ProductId && c.UserId == userId).First();
                oldCart.Count -= cart.Count;

                if (oldCart.Count == 0)
                    db.Carts.Remove(oldCart);

                db.SaveChanges();

            }
            catch (Exception)
            {

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "User,Contributor,Admin")]
        public IActionResult UpdateCart(Cart cart)
        {

            string userId = _userManager.GetUserId(User);
            try
            {
                Cart oldCart = db.Carts.Where(c => c.ProductId == cart.ProductId && c.UserId == userId).First();

                oldCart.Count += cart.Count;
            }
            catch
            {
                cart.UserId = userId;
                db.Carts.Add(cart);
            }
            db.SaveChanges();

            //return RedirectToAction("Show", "Products", new {id = cart.ProductId});
            return RedirectToAction("Index");
        }
    }
}

LittleFarmCakes/Controllers/CategoriesController.cs
using LittleFarmCakes.Data;
using LittleFarmCakes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LittleFarmCakes.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {

        private readonly ApplicationDbContext db;

        public CategoriesController(ApplicationDbContext context)
        {
            db = context;
        }
        public ActionResult Index()
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            var categories = from category in db.Categories
                             orderby category.CategoryName
                             select category;
            ViewBag.Categories = categories;
            return View();
        }

        public ActionResult Show(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(Category cat)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(cat);
                db.SaveChanges();
                TempData["message"] = "Categoria a fost adaugata";
                return RedirectToAction("Index");
            }

            else
            {
                return View(cat);
            }
        }

        public ActionResult Edit(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(int id, Category requestCategory)
        {
            Category category = db.Categories.Find(id);

            if (ModelState.IsValid)
            {

                category.CategoryName = requestCategory.CategoryName;
                db.SaveChanges();
                TempData["message"] = "Categoria a fost modificata!";
                return RedirectToAction("Index");
            }
            else
            {
                return View(requestCategory);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            TempData["message"] = "Categoria a fost stearsa";
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

LittleFarmCakes/Controllers/UsersController.cs
using LittleFarmCakes.Data;
using LittleFarmCakes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace LittleFarmCakes.Controllers
{
    public class UsersController : Controller
    {
            private readonly ApplicationDbContext db;
            private readonly UserManager<ApplicationUser> _userManager;
            private readonly RoleManager<IdentityRole> _roleManager;
            private readonly IWebHostEnvironment _env;
            public UsersController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
            IWebHostEnvironment env
            )
            {
                db = context;
                _userManager = userManager;
                _roleManager = roleManager;
                _env = env;
            }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var userRoles = db.UserRoles.Include("User").Include("Role");

            ViewBag.UserRoles = userRoles;
            ViewBag.Roles = GetAllRoles();

            if(TempData.ContainsKey("Message"))
            {
                ViewBag.Message = TempData["Message"];
            }

            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(string id)
        {
            try
            {
                var userRole = db.UserRoles.Include("User").Where(u => u.UserId == id).First();
                userRole.UpdateRole = GetAllRoles();

                return View(userRole);
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(ApplicationUserRole userRole)
        {
           
                var oldUser = db.UserRoles.Where(u => u.UserId == userRole.UserId).First();
                ApplicationUserRole update = new ApplicationUserRole();
                update.UserId = userRole.UserId;
                update.RoleId = userRole.RoleId;
                db.UserRoles.Remove(oldUser);
                db.UserRoles.Add(update);

                TempData["Message"] = "Userul a fost updatat";

                db.SaveChanges();
                return RedirectToAction("Index");
        }

    [NonAction]
    public IEnumerable<SelectListItem> GetAllRoles()
    {
        var selectList = new List<SelectListItem>();

        var roles = from role in db.Roles
                         select role;

        foreach (var role in roles)
        {

            selectList.Add(new SelectListItem
            {
                Value = role.Id.ToString(),
                Text = role.Name.ToString()
            });
        }

        return selectList;
    }

}
}

LittleFarmCakes/Views/Shared/ProductInfo.cshtml
@{
    ViewBag.Image = "https://static.vecteezy.com/system/resources/thumbnails/009/357/549/small_2x/eps10-grey-cake-line-icon-isolated-on-white-background-cake-with-candles-outline-symbol-in-a-simple-flat-trendy-modern-style-for-your-web-site-design-logo-pictogram-and-mobile-application-free-vector.jpg";
}



<div class="card d-flex w-100 flex-row my-2 productInfo h-auto pb-3">
    <img class="card-img-top m-to img2" src="@Model.Picture" onerror="this.onerror=null;this.src='@ViewBag.Image'" alt="Nu exista o imagine disponibila">
    <div class="card-body d-flex flex-column w-100">
        <div class="d-flex flex-row justify-content-between h-auto">
            <h5 class="card-title title">@Model.Title</h5>
            <div class="flex-grow-1"></div>
            @if (Model.Rating != 0)
            {
                <div class="justify-content-end">Rating: @Model.Rating</div>
            }
        </div>
        <div class="card-text">@Html.Raw(Model.Description)</div>
        <div class="h-auto w-100 mb-3">
            <i class="bi bi-globe"></i> @Model.Category.CategoryName
        </div>
    </div>
</div>

LittleFarmCakes/Views/Shared/ValidateInfo.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<div class="card d-flex w-100 flex-row my-2">
    <img class="card-img-top w-25 border border-primary m-to img2" src="@Model.Picture" alt="Nu exista o imagine disponibila">
    <div class="card-body d-flex flex-column w-100">
        <div class="d-flex flex-row justify-content-between">
            <h5 class="card-title h-25">@Model.Title</h5>
        </div>
        <p class="card-text h-50 w-100">@Model.Description</p>
        <div class="h-25 w-100">

            <br />
            <div><i class="bi bi-globe"></i> @Model.Category.CategoryName</div>
        </div>
    </div>
</div>

        

LittleFarmCakes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LittleFarmCakes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LittleFarmCakes.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <!-- se include summernote css -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 navbar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LittleFarmCakes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Afisare produse</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Carts" asp-action="Index">Afiseaza cos</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Afisare categorii</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="New">Adaugare produs</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Validate">Valideaza produse</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Afisare useri</a>
                            </li>

                        }

                        @if (User.IsInRole("Contributor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Afisare produse</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Carts" asp-action="Index">Afiseaza cos</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="New">Adaugare produs</a>
                            </li>
                        }

                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Afisare produse</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Carts" asp-action="Index">Afiseaza cos</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LittleFarmCakes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>

    <script src="~/js/Summernote.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LittleFarmCakes/Views/Shared/_LayoutNou.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArticlesApp.styles.css" asp-append-version="true" />
</head>

<header>
    <div class="container">
        <div class="col-md-6 offset-3 mt-5">

            <h2>Header</h2>

        </div>
    </div>
</header>

<body>
    <div class="container">
        <div class="col-md-6 offset-3">

            @RenderBody()

        </div>
    </div>
</body>

<footer>
    <div class="container">
        <div class="col-md-6 offset-3">

            <h2>Footer</h2>

        </div>
    </div>
</footer>
</html>